version: '2' # required to adjust maintainability checks

checks:
  file-lines:
    enabled: false
  method-lines:
    enabled: false

exclude_patterns:
  # Exclude settings objects
  - 'src/main/kotlin/com/chemistsmc/chatenhancer/config/*Settings.kt'
  # Exclude Patterns class because it has a lot of repetition in the Regex's
  - 'src/main/kotlin/com/chemistsmc/chatenhancer/util/Patterns.kt'
  # Don't check test classes
  - 'src/test/kotlin/**/*Test.java'
