# Text to place in front of messages sent from the plugin
# Essentially, the this is the display name for the bot
chatbot-prefix: '&2ChatBot:&7'

# Settings for all of the included default modules
modules:
  mentions:
    # Enable or disable the player mentions module
    enabled: true
    # Color used for mention highlights
    # See http://ess.khhq.net/mc/ for valid codes
    # Default: yellow, bold
    color: '&e&l'
  replacer:
    # Enable or disable the text replacer module
    enabled: true
  slaps:
    # Enable or disable the slapping module
    enabled: true
