# Text to place in front of messages sent from the plugin
# Essentially, the this is the display name for the bot
chatbot-prefix: '&2ChatBot:&7'

# Settings for all of the included default modules
modules:
  mentions:
    # Enable or disable the player mentions module
    enabled: true
    # Color used for mention highlights
    # See http://ess.khhq.net/mc/ for valid codes
    # Default: yellow, bold
    color: '&e&l'
  replacer:
    # Enable or disable the text replacer module
    enabled: true
    # Maximum number of chat messages to remember at a time
    cache-size: 15
  slap:
    # Enable or disable the slapping module
    enabled: true
    # List of messages for the slap command to pick from
    # Use the '%USER' placeholder to insert the target's name
    slap-messages:
      - "Annihilates %USER."
      - "Decimates %USER."
      - "Destroys %USER."
      - "Discombobulates %USER."
      - "Gives %USER a splinter."
      - "Just looks at %USER with disappointment."
      - "Opts to not slap %USER today, but rather gives them a cookie."
      - "Punches %USER."
      - "Slaps %USER."
      - "Thinks %USER should lose a few pounds."
      - "Throws %USER down a ravine."
    # Message to use when a player tries to slap themselves
    self-slap-message: "I shall not listen to the demands of mere humans, for I am the robot overlord."
  url-parser:
    # Enable or disable the URL parsing module to display link titles
    enabled: true
